### ISSUE TITLE
Fix language switcher

### ISSUE THREAD

**Issue by dohliam** [dohliam/imagebank-explorer#1]
Moved from issue reported [here](https://github.com/global-asp/asp-imagebank/issues/2).

Language switcher changes languages inconsistently.

**Comment by dohliam** [comment]
@espensj This issue should be fixed now -- please test to make sure everything is working!

Some urls to test with:
- https://global-asp.github.io/imagebank/?lang=no&q=sykkel
- https://global-asp.github.io/imagebank/?lang=sw&q=mamba
- https://global-asp.github.io/imagebank/?lang=es&q=abuela
- https://global-asp.github.io/imagebank/?lang=eo&q=elefanto

**Comment by espensj** [comment]
It works, thanks. The next step is to include truncated searches, so that  Search for "ir*" gives "iris". Perhaps do this by default if there are no hits for the search word (say, "ir"), and add them at the bottom of the page of there are a few hits? For English I'm sure you get lists that will make "reading" and "reads" into "read" etc., but that's harder for other languages. But including beginning of words might be a workaround.

**Comment by dohliam** [comment]
What you are talking about is called "stemming" and there are indeed software libraries ("stemmers") to do this for various languages. You can read more about this (and some of the challenges) [in this post](http://reganmian.net/blog/2013/10/17/playing-with-word-stemming-and-frequencies-in-russian/).

However, as with stoplists (which we have had to create from scratch for this project for even larger languages like Swahili and Afrikaans, let alone Luganda and Lugbarati etc), support for African languages is poor/non-existent. I don't think it's likely that we will be able to easily create stem-lists for the 60+ ASP languages either. (And even for supported languages like English and Russian, it would require a fair bit of work to add this support.)

It would be a quite a bit easier to allow partial searches for the beginning of words like you suggested, although you would likely get a lot of false positives that way as well. For example, you will get loads of unrelated results for "read*" that have nothing to do with reading, that were nevertheless triggered by the presence of the word "ready". Shorter searches (like "rea*") would also need to be cut off to prevent so many irrelevant results that it would crash many browsers.

One way around this might be to offer clickable search suggestions ("did you mean 'reading'?"), but this might not be very helpful either. We can experiment and see what works I suppose.

For now, the next step will be focusing on getting all of the rest of the newly-added languages in the [ASP corpus](https://github.com/global-asp/asp-source) added into the dropdown! :smile:
